# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:14
from __future__ import unicode_literals

from django.db import migrations


def add_some_stuff(apps, schema_editor):
    # do anything...
    pass


def undo_some_stuff(apps, schema_editor):
    # undo everything
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20160630_1820'),
    ]

    operations = [
        migrations.RunPython(add_some_stuff, undo_some_stuff)
    ]
